# Generated by Django 5.0.4 on 2024-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1App', '0004_driver_driverphoto_grandprix_gpphoto_team_teamphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
