# Generated by Django 5.0.4 on 2024-05-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1App', '0006_alter_driver_driverhistory_alter_team_teamhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driverPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='front-end/src/assets/driver_photos/'),
        ),
        migrations.AlterField(
            model_name='grandprix',
            name='gpPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='front-end/src/assets/gp_photos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='front-end/src/assets/team_photos/'),
        ),
    ]
