# Generated by Django 5.0.4 on 2024-05-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1App', '0007_alter_driver_driverphoto_alter_grandprix_gpphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driverPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='gp_photos/'),
        ),
        migrations.AlterField(
            model_name='grandprix',
            name='gpPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='gp_photos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
    ]
