# Generated by Django 5.0.4 on 2024-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1App', '0011_raceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandprix',
            name='country',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
