# Generated by Django 5.0.4 on 2024-05-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1App', '0013_driver_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandprix',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
