# Generated by Django 5.0.4 on 2024-05-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formula1App', '0015_alter_grandprix_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
